### PR TITLE
Migrate to six

### PR DESCRIPTION
**Pull request by bmwant**
## Rationale

For easier migration to Python 3 use `six` library that allows writing code compatible with both Python 2/3 versions easier.
## Changes
- Refactor some docstring and code style issues
- Replace all compatible code to use `six`
- Add `Makefile` with some common recipes
- Update `setup.py` file

### CODE REVIEW

**Comment by lechat** [comment]
Wow! That's big code chunk and thank you for that.

But why use six? Any particular thing that is hard to achieve in current library and is easy with six? 

I'd rather keep library dependencies as lean as possible and try not to make it dependant on everything.

**Comment by salimfadhley** [comment]
Six is just a bunch of mappings to even out the api differences between
versions. It's well maintained and way safer than adding explicit code to
handle version differences.

**Comment by bmwant** [comment]
Ok, so some main points for the migration:
* Relying on the `ImportError` and `NameError` may cause interception of some other errors within one version
* Using same block of code will eliminate code duplication therefore making code less error-prone rather than have different blocks for each python version 
* You can forgot particular difference of implementation and six will abstract that for you
* `try-except` block contains much more space than `six.iteritems` obviously and the same for other things
* It's single file ~800 loc, not a huge dependency and it's a common library for 2/3 compatibility

There is not such term as "thing hard to achieve", but rather more cleaner and idiomatic approach and best practice in general. If you're developing package that should be portable between Python versions than you should consider using tools aimed for that.

@lechat I'm gonna give you the benefit of the doubt on this one, but from my perspective it's better to use six here.

**Comment by lechat** [comment]
I've created pull request for my pytest conversion work. Not all tests converted yet but I'd rather not do rework on all converted tests in order to incorporate changes in this PR. 

@bmwant would you mind updating your code once I merge #508?

**Comment by bmwant** [comment]
@lechat sure, will update my code after py.test successful integration

**Comment by lechat** [comment]
I've merged pytest conversion branch, could you update your code? Many thanks!

**Comment by bmwant** [comment]
@lechat yes, but probably during next week

**Comment by bmwant** [comment]
@lechat This one needs review

**Pull request merged**
