### PR TITLE
add utf8 encoding to support invoking jobs with unicode build params

### PR DESCRIPTION
**Pull request by Leshist**

### CODE REVIEW

**Comment by bmwant** [comment]
@Leshist it will not work that way. You need either call `encode` on `str` value or check if `v` variable is actually string. And also add test to cover this case

**Comment by lechat** [comment]
Yes, the test is required. And, of course, that kind of change must work on different python versions.

**Comment by Leshist** [comment]
added unit test and python3 compatibility

**Comment by bmwant** [comment]
@lechat Looks good to me, any additional feedback?

**Pull request merged**
