### PR TITLE
Added CrumbRequester

### PR DESCRIPTION
**Pull request by lechat**
This fix is for issue #300

### CODE REVIEW

**Comment by whereskenneth** [comment]
Can you explain how this is used?

I am getting problems kicking off build jobs on server with CSRF protection enabled. The server response indicates a crumb is missing. 

This class is added to fix that - great! But I fail to see how it's used within the context of the rest of the module.

**Comment by lechat** [comment]
You need to pass it to `Jenkins` class:

```python
from jenkinsapi.utils.crumb_requester import CrumbRequester


crumb_requester = CrumbRequester(baseurl='http://localhost:8080', username='admin', password='admin123')
jenkins = Jenkins('http://localhost:8080', username='admin', password='admin123', requester=crumb_requester)
```

**Comment by whereskenneth** [comment]
Thanks @lechat. 

I confused myself a little bit - I thought this was in 0.3.1, and was freaking out a little bit when I couldn't find it in that release. 

It looks like 0.3.1 was cut just before this was merged into master.

**Comment by lechat** [comment]
Yes, 0.3.1 was done to fix major issue with Jobs. I decided to not release code with CrumbRequester before I test it, but now you tested it for me. :)

**Comment by lechat** [comment]
Released 0.3.2 to PYPI

**Comment by whereskenneth** [comment]
Working well. Thanks.

**Pull request merged**
