### PR TITLE
Feature/multibranch pipeline job

### PR DESCRIPTION
**Pull request by chrismaes87**
implementation of a jenkins.create_multibranch_pipeline_job() method.

Feel free to comment, some of this are workarounds, which I am not so happy about but I didn't find another way to implement it.

I'm also having trouble testing this because for true tests we would need some kind of repository. I tried creating a repository on github but I bump on limited API requests... Some help or hints would be appreciated.

### CODE REVIEW

**Comment by lechat** [comment]
Thank you for this!

My guess, while Travis is still building, that test will fail because required plugins are not present in Jenkins instance started by tests.

The list of plugins installed is here: https://github.com/pycontribs/jenkinsapi/blob/master/jenkinsapi_tests/systests/conftest.py#L15

The Jenkins launcher is here: https://github.com/pycontribs/jenkinsapi/blob/master/jenkinsapi_utils/jenkins_launcher.py

**Comment by lechat** [comment]
I also suggest asking plugin developer(s) to provide REST API for polling of status and getting list of jobs.

**Comment by chrismaes87** [comment]
ok, I'll try to get the list of plugins complete. But the other problem will be more blocking, I have multiple issues with the implementation of my tests:

- github API is restricting polling so much I can't even use it for testing; where to get a decent testing repository
- testing now depends on a dummy repository in my github account, that doesn't feel like a clean solution.

any hints on these? I have tested the code locally with our internal bitbucket instance and that worked, but I fail to see how to make these tests clean and working.

**Comment by lechat** [comment]
The only way to deal with such problems is to use mocks in unit tests. I prefer system tests, but in some cases it is impossible to test like that. 
Last thing I want to add to a library is test dependency on your private repository. Things change, it may cease to exist and will create problems.

**Comment by chrismaes87** [comment]
I totally agree, that's why I brought the issues up. I'm rewriting with a unit-test.

**Comment by chrismaes87** [comment]
I was thinking about this still. Looping through all jobs might take much time. So either I should refactor in order to speed up searching for the good jobs, either the return value should just be a Boolean and I could add a other convenience function to find all jobs matching a pattern.

What do you think?

**Comment by chrismaes87** [comment]
> I was thinking about this still. Looping through all jobs might take much time. So either I should refactor in order to speed up searching for the good jobs, either the return value should just be a Boolean and I could add a other convenience function to find all jobs matching a pattern.
> 
> What do you think?

I just implemented a speedup using get_jobs_list() instead of get_jobs(). Feel free to tell me if you prefer another implementation.

**Comment by chrismaes87** [comment]
build failed because of some connection that was lost, seems not to be linked to my PR...

**Pull request merged**
