### PR TITLE
Enabled flaky tests

### PR DESCRIPTION
**Pull request by ssbarnea**
Workaround for avoiding common test
failures on Travis.

Change-Id: Iaa32d5f8a93fc18906dbf9609de7ce0dbde04317

### CODE REVIEW

**Comment by salimfadhley** [comment]
Can you explain the rationale for this change? We shouldn't have any tests whose behavior is non-deterministic.

**Comment by ssbarnea** [comment]
Sure: I am almost sure that the current errors are due to timeouts from Jenkins backend. They are likely to happen on Travis because the machines are slower.

My goal is not to make this permanent but to implement a resilience mechanism in the library itself so when the backend is not available, to retry at least once, after a delay. This would apply only to for HTTP codes that are retriable. 

I did something like this few years ago for the Python JIRA library, see https://github.com/jameskeane/jira-python/blob/master/jira/resilientsession.py

Few things changes since then, now Requests library has adopted some retry mechanism itself so it may be even easier to enable it.

**Comment by ssbarnea** [comment]
@salimfadhley And regarding your original question: have a look at this https://travis-ci.org/pycontribs/jenkinsapi/builds/246338549 -- my impression is that's example of tests that may not produce deterministic results.

I am more than interested to hear you ideas about how to assure that our Travis executions are reliable.

**Comment by ssbarnea** [comment]
Abandoning this because I had another single line change that addressed the flakiness during testing.

**Pull request closed without merging**
