### PR TITLE
Support keyworded variables for requester, fixes #679

### LINKED ISSUE #679: Connection failed with crumb requester as 403 Client Error: Forbidden
##### ISSUE TYPE

 - Bug Report

##### Jenkinsapi VERSION
0.3.7
##### Jenkins VERSION
Jenkins ver. 2.150.1
##### SUMMARY

Looks like in the latest release the connection to a jenkins instance that has CSRF protection enabled is not working anymore.
For example by executing:
```
#!/usr/bin/env python3

from jenkinsapi.jenkins import Jenkins
from jenkinsapi.utils.crumb_requester import CrumbRequester

jenkins = Jenkins(
    'http://localhost:8080', username='test', password='test',
    requester=CrumbRequester(
        baseurl='http://localhost:8080',
        username='test',
        password='test'
    )
)

for job_name in jenkins.jobs:
    print (job_name)
```
##### EXPECTED RESULTS

Print all the jobs currently available on the jenkins instance.
In the previous version (0.3.6) the above code just worked fine.
##### ACTUAL RESULTS

Getting 403 forbidden when instantiating a new Jenkins object.
The stacktrace is:
```
ERROR:root:Failed request at http://localhost:8080/api/python with params: {'tree': 'jobs[name,color,url]'} jobs[name,color,url]
Traceback (most recent call last):
  File "./test.py", line 11, in <module>
    password='test'
  File "/usr/local/lib/python3.6/dist-packages/jenkinsapi/jenkins.py", line 63, in __init__
    JenkinsBase.__init__(self, baseurl, poll=not lazy)
  File "/usr/local/lib/python3.6/dist-packages/jenkinsapi/jenkinsbase.py", line 35, in __init__
    self.poll()
  File "/usr/local/lib/python3.6/dist-packages/jenkinsapi/jenkinsbase.py", line 57, in poll
    data = self._poll(tree=tree)
  File "/usr/local/lib/python3.6/dist-packages/jenkinsapi/jenkins.py", line 68, in _poll
    if not tree else tree)
  File "/usr/local/lib/python3.6/dist-packages/jenkinsapi/jenkinsbase.py", line 81, in get_data
    response.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 935, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: http://localhost:8080/api/python?tree=jobs%5Bname%2Ccolor%2Curl%5D
```
##### USEFUL INFORMATION

Just run the code above using both 0.3.6 and 0.3.7 and compare output.

### PR DESCRIPTION
**Pull request by JonasVerhofste**

### CODE REVIEW

**Comment by JonasVerhofste** [comment]
Could someone explain to me what line [line 46](https://github.com/pycontribs/jenkinsapi/blob/master/jenkinsapi/utils/requester.py#L46) and 47 do? An error gets raised anyway, why surround it with a try-block and redefine it manually?

**Comment by lechat** [comment]
I think that this change will break some existing code because it implies that username ans password must be named parameters. Better code would be to leave current functionality and add check to see if unnamed parameters were not passed and only then use named ones.

**Comment by JonasVerhofste** [comment]
> because it implies that username ans password must be named parameters.
I don't think it does? I set the default value of the named parameter to the unnamed one created above. That's the second parameter of the get-command: it's the default value when a keyword is not found in a dictionary. Seeing as kwargs is just a dictionary with keyword-value pairs.

I just tested it and `CrumbRequester(username, password, baseurl=url)` and `CrumbRequester(username=username, password=password, baseurl=url)` both work. Could set up a test-case, should you want it.

**Comment by lechat** [comment]
Yes, you are right. Please make unit test and I will accept this PR. Thank you!

**Pull request merged**
