### PR TITLE
jobs.py: don't yield jobs twice

### PR DESCRIPTION
**Pull request by chrismaes87**

### CODE REVIEW

**Comment by chrismaes87** [comment]
please merge this into master and create a new version. I have developments that depend on this bugfix...

**Comment by chrismaes87** [comment]
@lechat would it be possible to create a new version? I have developments depending on this bugfix.

**Comment by chrismaes87** [comment]
could someone just create a new release for this? Just setting a tag it seems to me?

**Comment by lechat** [comment]
Released 0.3.11

**Comment by alfredoport** [comment]
What was the purpose of this PR? (there is no description). It appears to break current implementations searching using jobname.

**Comment by chrismaes87** [comment]
I use MultiBranch pipelines. each one of my branches is thus represented as a Jenkins job. Each one was represented twice, due to the double `yield`: "job/master" and "master".
So two undesired results for me:

- all jobs were present twice in the job_list
- many jobs with the name "master" which is of no use because I cannot select on that name (not unique)

**Comment by alfredoport** [comment]
@chrismaes87 thanks. Apparently due to the double yield, one was able to reference a job by name, regardless if the job was in a folder.

```
if job.name != job.get_full_name():
    yield job.get_full_name(), job
else:
    yield job.name, job
```

This forces that you cannot have the "full_name" and "name" in the iteration, which I imagine was the original intent.

**Pull request merged**
