### PR TITLE
Add get_env_vars to Build

### LINKED ISSUE #489: support getting environment variables
##### ISSUE TYPE
- Feature Idea
##### Jenkins VERSION

2.9
##### SUMMARY

The REST API to get env variables from the build is present.
I think it would be great if jenkinsapi supported getting these variables.
https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin

### PR DESCRIPTION
**Pull request by ripcurld0**
The build environment varialbes can be obtained from Jenkins thanks to the EnvInject plugin:
https://wiki.jenkins-ci.org/display/JENKINS/EnvInject+Plugin

To support that in JenkinsAPI the get_env_vars method was added to the Build class.

closes #489

### CODE REVIEW

**Comment by lechat** [comment]
Why not adding systest? It is much easier to work with Jenkins compared to working with mocks. Plus this approach guarantees that the change works, while unit test guaranteed that unittest works and nothing more.

**Comment by ripcurld0** [comment]
@lechat thanks for that. I will add tests to the systest. 🥇

**Comment by ripcurld0** [comment]
//ping @lechat

**Comment by chiccat** [comment]
Hey @boaz1337 ,
How to use this?
I do have everything installed, but when I go injectedEnvVars/export or injectedEnvVars/api/python Jenkins redirects me back to the job.
Thanks

**Pull request merged**
